# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Strapongo\Projects\Hw PyQt\Lab3\passwords_checker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 349)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exceptionsList = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.exceptionsList.setGeometry(QtCore.QRect(20, 30, 251, 291))
        self.exceptionsList.setReadOnly(True)
        self.exceptionsList.setObjectName("exceptionsList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
