# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Strapongo\Projects\Hw PyQt\Lab3\reg_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 164)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signButton = QtWidgets.QPushButton(self.centralwidget)
        self.signButton.setGeometry(QtCore.QRect(320, 70, 93, 28))
        self.signButton.setObjectName("signButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 261, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginEdit = QtWidgets.QLineEdit(self.widget)
        self.loginEdit.setObjectName("loginEdit")
        self.verticalLayout.addWidget(self.loginEdit)
        self.pswdEdit = QtWidgets.QLineEdit(self.widget)
        self.pswdEdit.setObjectName("pswdEdit")
        self.verticalLayout.addWidget(self.pswdEdit)
        self.phoneEdit = QtWidgets.QLineEdit(self.widget)
        self.phoneEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.phoneEdit.setObjectName("phoneEdit")
        self.verticalLayout.addWidget(self.phoneEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signButton.setText(_translate("MainWindow", "Sign up"))
        self.loginEdit.setPlaceholderText(_translate("MainWindow", "login"))
        self.pswdEdit.setPlaceholderText(_translate("MainWindow", "password"))
        self.phoneEdit.setPlaceholderText(_translate("MainWindow", "phone number"))
